spring:
  application:
    name: application
  datasource:
    url: jdbc:postgresql://localhost:6578/delivery
    username: postgres
    password: root
  jpa:
    properties:
      show-sql: true
      format_sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
  port: 6812